### ISSUE TITLE
Remove trailing whitespace on _current_ line

### ISSUE THREAD

**Issue by radicaled** [atom/whitespace#42]
I seem to end up with a lot of trailing whitespace in my files when those trailing lines are after the cursor's position. I guess they're the result of me tabbing twice or something?

Is it possible to add an exception to "Ignore whitespace on current line" so that trailing whitespace is still trimmed, while whitespace preceding the cursor is still intact?

**Comment by mquandalle** [comment]
It seems that a setting has been implemented for this feature — and default to ignore whitespace on current line.

**Comment by radicaled** [comment]
"Ignore whitespace on current line" is a little bit different. Image `$` is your cursor, and `.` is whitespace.

Initial file:
```
.....$.....
```

Saving with "Ignore whitespace on current line" enabled

```
.....$.....
```

Saving with "Ignore whitespace on current line" disabled

```
$
```

What I would love, instead, is for this to happen on a save:

```
.....$
```

**Comment by mquandalle** [comment]
Is there any case where we want the current default behavior for the current line (`.....$.....`)? I can't think of any, but I may miss something.

**Comment by radicaled** [comment]
I've assumed the entire time the current behavior exists just because `whitespace` uses a very naive method of removing trailing whitespace: it uses a regular expression on every line in the current buffer, excluding the current line if a cursor is present there and the appropriate option is selected. (see: https://github.com/atom/whitespace/blob/master/lib/whitespace.coffee#L55 )

Implementing this feature would mean refactoring the logic so that it tracks cursor position to the character, subselecting everything on the line beyond the cursor, performing the trailing whitespace removal, and then updating the current line without disrupting the location of any cursor on that line.

So, compared to the current implementation, nontrivial.

But I never got any feedback on this issue, so I don't know if that's the real reason or it was just an oversight in developing the package.

I don't think there's any real reason you'd want to leave trailing whitespace beyond the current cursor position.

**Comment by aseemk** [comment]
I generally like the default option here, to leave my current line alone, but a few times now I've committed with trailing whitespace, not realizing my last save must have been on a blank line with indentation.

Is it technically possible to still strip trailing whitespace on the current line, *but to leave the cursor intact in its original position*?

I'm not sure how Atom works, but e.g. TextMate lets you option-click to place the cursor anywhere in the file, even if there aren't tabs/spaces to get there yet. (And it doesn't add any until/unless you actually start typing there.)

Thanks! And keep up the great work. =)

P.S. I appreciate how both this plugin and this option are enabled by default.

**Comment by mquandalle** [comment]
> Is it technically possible to still strip trailing whitespace on the current line, but to leave the cursor intact in its original position?

I think it's exactly what @radicaled is proposing ;-)

**Comment by aseemk** [comment]
Sorry, to be clear, I meant that *all spaces* (including before your cursor) would still get stripped — but your cursor would *appear to* remain at the same spot.

Before stripping whitespace:

```
....
....foo
....$...
....bar
....
```

After:

```

....foo
    $
....bar

```

Notice how all the whitespace on that (empty) line has been stripped — but the cursor remains indented where it was.

Upon *any single character keystroke* then, e.g. `x`, the indentation would get (re-)added:


```

....foo
....x$
....bar

```

Hope that clarifies, and apologies if that's also what @radicaled meant.

Thanks for the consideration! =)

**Comment by aseemk** [comment]
Btw, I should mention that my primary motivation for this request is to keep me in The Flow™. =)

It's nice not to have the cursor position change when I (instinctively) save the file, but it's also nice to strip the whitespace on the current line if it turns out I'm done.

**Comment by schuylr** [comment]
Bump. I can reproduce this issue still on my Atom. Is there any progress on this or did this just get lost in the woodwork?

**Comment by chesterbr** [comment]
Also a problem for me - I often save regardless of cursor position, and only realize in CI lint the current line had extra space (without ever imagining why it is so special and different from other lines). At least a setting that made it work like other lines would be <3 (and I wonder why it isn't the default). Thanks!
